### ISSUE TITLE
Migrate forum.bisq.io => bisq.community

### ISSUE THREAD

**Issue by cbeams** [bisq-network/forum#3]

**Comment by alexej996** [comment]
In order to migrate Bisq forum to a new server following tasks require to be completed:

- [x] Forum software on both servers should run the latest Discourse version. (currently the old server is running an older version of the software and needs to be updated from a command-line, which requires ssh access)

- [x] Backup of the forum needs to be created on the old server, uploaded to the new server and the new server needs to restore from that backup.
(Discourse allows for backups to be downloaded using the admin panel by sending an email with a download link to the admin that requests the download. Unfortunately I lot access to my email months ago and was unable to change it without a command-line access to the server, so some other admin could send me a link or someone with ssh access could go through the proccess of changing the email of a staff member from the command-line as seen [here](https://meta.discourse.org/t/change-staff-email-address-from-console/42062?source_topic_id=30643) )

- [x] Old domain needs to redirect to the new domain as soon as possible to avoid content of the forums to fork by users still using the old forum. (it makes sense to stop the server right after the last backup is done, as any activity on the forum will not get transfered to the new server)

**Comment by Emzy** [comment]
Detailed discussion via mail. Because somehow security involved.

**Comment by cbeams** [comment]
> Detailed discussion via mail. Because somehow security involved.

I've created a private discussion thread at https://github.com/orgs/bisq-network/teams/forum-operators/discussions/1. Let's try that out for any further sensitive stuff, yeah?

**Comment by cbeams** [comment]
Closing as complete. Thanks, @alexej996!

https://forum.bisq.io now redirects to https://bisq.community.

@Emzy, are you good to decommission the server that was backing forum.bisq.io? Do you want to create an issue for that? Whatever you want to do is fine.
