### ISSUE TITLE
Activation emails are not being delivered

### ISSUE THREAD

**Issue by cbeams** [bisq-network/forum#6]
Perhaps related to #5 (which may never have been fully solved?), I've just gotten another report of a user who cannot get their activation email from the forum.

@bisq-network/forum-operators, please do whatever it takes to nail this down. Perhaps it means moving to a different mail provider. In any case, let's make sure we thoroughly test whatever solution we come up, thanks.

From https://twitter.com/olthoff/status/997871590049132545

![image](https://user-images.githubusercontent.com/301810/40275959-201db960-5bfe-11e8-8526-38e9b011c576.png)

**Comment by alexej996** [comment]
You are correct. There is an issue with the limit of emails we can send each day (the limit is 200).
It seems like every week we have a sudden increase in emails that need to be sent out, which I assume is digest emails, which creates this backlog for couple of days.

This limit is simply due to the free plan that I use at Mailjet, we would have to pay to have more than 200 emails sent a day. But for now we seem to be having very small amount of active users and a lot of emails being sent out to users that only logged in few times to the forum (about 10 emails for every active user). So I think the easiest solution for now would be to disable digest emails for all users, but let them enable it in the settings if they want.

We already had to disable digest emails by default for new users to solve #5 , so these emails aren't considered spam, but I left already existing user's preferences as they were. I guess I will disable it for everyone now and let users know about it so they can enable them by themselves if they still want to receive digest emails.

I have plans on running a mail server so we don't have to deal with these limits anymore, but that will have to wait a bit until I figure out how to best configure a mail server on Ubuntu, since the forum server runs this OS and I only configured OpenBSD mail server before.

**Comment by cbeams** [comment]
Thanks, @alexej996. Not too surprising, I think, that we would hit a 200-mails-per-day limit on a regular basis. I'm not sure what the fastest and easiest way to remedy this is, but one obvious one would be moving to a paid level and adding that to your compensation requests every month. I understand if that's not feasible or desirable to you to foot the bill while we're still in Phase Zero, but if it *is* an option, even in the meantime while figuring out what to do with your own mail server, then great.

@Emzy, do you have any recommendations for @alexej996 on setting up this mail server? Is this something you could assist with in some way?

**Comment by alexej996** [comment]
Closing this as I have setup our own mail server months ago. It is still not used though, as our mailing provider still seems to do the job well for now.
